#ifndef VECTOR_VISUALIZER_3D_SRC_CORE_SHADERS_SHADERLOADER_H_
#define VECTOR_VISUALIZER_3D_SRC_CORE_SHADERS_SHADERLOADER_H_

namespace ShaderLoader {

class ShaderLoader {

};

} // ShaderLoader

#endif //VECTOR_VISUALIZER_3D_SRC_CORE_SHADERS_SHADERLOADER_H_
