#ifndef VECTOR_VISUALIZER_3D_SRC_ENGINE_CORE_UTILS_H_
#define VECTOR_VISUALIZER_3D_SRC_ENGINE_CORE_UTILS_H_

#ifdef DEBUG
#define ON_DEBUG(x) x
#endif

#endif //VECTOR_VISUALIZER_3D_SRC_ENGINE_CORE_UTILS_H_
